// This file is auto-generated by @hey-api/openapi-ts

export const AILogResponseSchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/ChatHistoryItem'
            },
            type: 'array',
            title: 'Items'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        limit: {
            type: 'integer',
            title: 'Limit'
        }
    },
    type: 'object',
    required: ['total', 'items', 'page', 'limit'],
    title: 'AILogResponse'
} as const;

export const Body_login_access_token_api_v1_auth_login_access_token_postSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login_access_token_api_v1_auth_login_access_token_post'
} as const;

export const Body_login_access_token_api_v1_login_access_token_postSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login_access_token_api_v1_login_access_token_post'
} as const;

export const Body_login_alias_api_v1_auth_login_postSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login_alias_api_v1_auth_login_post'
} as const;

export const BookmarkCreateSchema = {
    properties: {
        item_type: {
            type: 'string',
            title: 'Item Type'
        },
        item_neo4j_id: {
            type: 'string',
            title: 'Item Neo4J Id'
        }
    },
    type: 'object',
    required: ['item_type', 'item_neo4j_id'],
    title: 'BookmarkCreate'
} as const;

export const BookmarkListSchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/BookmarkResponse'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total', 'items'],
    title: 'BookmarkList'
} as const;

export const BookmarkResponseSchema = {
    properties: {
        item_type: {
            type: 'string',
            title: 'Item Type'
        },
        item_neo4j_id: {
            type: 'string',
            title: 'Item Neo4J Id'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        user_id: {
            type: 'integer',
            title: 'User Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['item_type', 'item_neo4j_id', 'id', 'user_id', 'created_at'],
    title: 'BookmarkResponse'
} as const;

export const ChatHistoryItemSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        response: {
            type: 'string',
            title: 'Response'
        },
        intent: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Intent'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'message', 'response', 'created_at'],
    title: 'ChatHistoryItem'
} as const;

export const ChatHistoryListSchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/ChatHistoryItem'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total', 'items'],
    title: 'ChatHistoryList'
} as const;

export const ChatMessageRequestSchema = {
    properties: {
        message: {
            type: 'string',
            maxLength: 1000,
            minLength: 1,
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'ChatMessageRequest'
} as const;

export const ChatMessageResponseSchema = {
    properties: {
        answer: {
            type: 'string',
            title: 'Answer'
        },
        entities: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Entities'
        },
        sources: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Sources'
        },
        warnings: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Warnings'
        }
    },
    type: 'object',
    required: ['answer'],
    title: 'ChatMessageResponse'
} as const;

export const DiseaseCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        severity: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Severity'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        treatments: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Treatments',
            description: 'List of medicine names that treat this disease'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'DiseaseCreate'
} as const;

export const DiseaseDetailResponseSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        severity: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Severity'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        symptoms: {
            items: {
                '$ref': '#/components/schemas/DiseaseSymptom'
            },
            type: 'array',
            title: 'Symptoms'
        },
        treatments: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Treatments',
            description: 'Medicine names'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'DiseaseDetailResponse',
    description: 'Disease detail response with symptoms.'
} as const;

export const DiseaseResponseSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        severity: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Severity'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'DiseaseResponse',
    description: 'Disease basic response.'
} as const;

export const DiseaseSearchResponseSchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        limit: {
            type: 'integer',
            title: 'Limit'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/DiseaseResponse'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total', 'limit', 'items'],
    title: 'DiseaseSearchResponse',
    description: 'Disease search response.'
} as const;

export const DiseaseSymptomSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'DiseaseSymptom',
    description: 'Disease symptom model.'
} as const;

export const DiseaseTreatmentResponseSchema = {
    properties: {
        disease_name: {
            type: 'string',
            title: 'Disease Name'
        },
        treatments: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Treatments',
            description: 'Medicine list with basic details'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['disease_name', 'total'],
    title: 'DiseaseTreatmentResponse',
    description: 'Response for medicines that treat a specific disease.'
} as const;

export const DiseaseUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        severity: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Severity'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        treatments: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Treatments'
        }
    },
    type: 'object',
    title: 'DiseaseUpdate'
} as const;

export const ForgotPasswordRequestSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'ForgotPasswordRequest',
    description: 'Forgot password request payload.'
} as const;

export const GraphNodeSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        properties: {
            additionalProperties: true,
            type: 'object',
            title: 'Properties'
        }
    },
    type: 'object',
    required: ['id', 'label', 'properties'],
    title: 'GraphNode'
} as const;

export const GraphRelationshipSchema = {
    properties: {
        source: {
            type: 'string',
            title: 'Source'
        },
        target: {
            type: 'string',
            title: 'Target'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        properties: {
            additionalProperties: true,
            type: 'object',
            title: 'Properties'
        }
    },
    type: 'object',
    required: ['source', 'target', 'type', 'properties'],
    title: 'GraphRelationship'
} as const;

export const GraphResponseSchema = {
    properties: {
        nodes: {
            items: {
                '$ref': '#/components/schemas/GraphNode'
            },
            type: 'array',
            title: 'Nodes'
        },
        links: {
            items: {
                '$ref': '#/components/schemas/GraphRelationship'
            },
            type: 'array',
            title: 'Links'
        }
    },
    type: 'object',
    required: ['nodes', 'links'],
    title: 'GraphResponse'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const InteractionCheckRequestSchema = {
    properties: {
        drug_names: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 10,
            minItems: 2,
            title: 'Drug Names'
        }
    },
    type: 'object',
    required: ['drug_names'],
    title: 'InteractionCheckRequest',
    description: 'Request to check interactions between drugs.'
} as const;

export const InteractionCheckResponseSchema = {
    properties: {
        results: {
            items: {
                '$ref': '#/components/schemas/InteractionResult'
            },
            type: 'array',
            title: 'Results'
        }
    },
    type: 'object',
    title: 'InteractionCheckResponse',
    description: 'Response for interaction check.'
} as const;

export const InteractionDetailResponseSchema = {
    properties: {
        drug_1: {
            type: 'string',
            title: 'Drug 1'
        },
        drug_2: {
            type: 'string',
            title: 'Drug 2'
        },
        has_interaction: {
            type: 'boolean',
            title: 'Has Interaction'
        },
        severity: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Severity'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message'
        }
    },
    type: 'object',
    required: ['drug_1', 'drug_2', 'has_interaction'],
    title: 'InteractionDetailResponse',
    description: 'Detailed interaction between two specific drugs.'
} as const;

export const InteractionListResponseSchema = {
    properties: {
        drug_name: {
            type: 'string',
            title: 'Drug Name'
        },
        interactions: {
            items: {
                '$ref': '#/components/schemas/InteractionResult'
            },
            type: 'array',
            title: 'Interactions'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message'
        }
    },
    type: 'object',
    required: ['drug_name', 'total'],
    title: 'InteractionListResponse',
    description: 'List of all interactions for a specific drug.'
} as const;

export const InteractionResultSchema = {
    properties: {
        drug_1: {
            type: 'string',
            title: 'Drug 1'
        },
        drug_2: {
            type: 'string',
            title: 'Drug 2'
        },
        has_interaction: {
            type: 'boolean',
            title: 'Has Interaction'
        },
        severity: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Severity'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['drug_1', 'drug_2', 'has_interaction'],
    title: 'InteractionResult',
    description: 'Interaction result between two drugs.'
} as const;

export const InteractionSummaryResponseSchema = {
    properties: {
        drug_names: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Drug Names'
        },
        interactions: {
            items: {
                '$ref': '#/components/schemas/InteractionResult'
            },
            type: 'array',
            title: 'Interactions'
        },
        is_safe: {
            type: 'boolean',
            title: 'Is Safe'
        },
        warnings: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Warnings'
        },
        summary: {
            type: 'string',
            title: 'Summary'
        }
    },
    type: 'object',
    required: ['drug_names', 'interactions', 'is_safe', 'summary'],
    title: 'InteractionSummaryResponse',
    description: 'Summary of drug combination analysis.'
} as const;

export const MedicineCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        brand_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand Name'
        },
        generic_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Generic Name'
        },
        manufacturer: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Manufacturer'
        },
        purpose: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Purpose'
        },
        indications: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Indications'
        },
        warnings: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Warnings'
        },
        dosage: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dosage'
        },
        contraindications: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contraindications'
        },
        adverse_reactions: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Adverse Reactions'
        },
        side_effects: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Side Effects'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'MedicineCreate'
} as const;

export const MedicineDetailResponseSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        brand_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand Name'
        },
        generic_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Generic Name'
        },
        manufacturer: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Manufacturer'
        },
        purpose: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Purpose'
        },
        indications: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Indications'
        },
        warnings: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Warnings'
        },
        dosage: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dosage'
        },
        contraindications: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contraindications'
        },
        adverse_reactions: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Adverse Reactions'
        },
        side_effects: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Side Effects'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        ingredients: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Ingredients',
            default: []
        },
        manufacturers: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Manufacturers',
            default: []
        },
        treated_diseases: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Treated Diseases',
            default: []
        },
        interactions: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Interactions',
            default: []
        }
    },
    type: 'object',
    required: ['name'],
    title: 'MedicineDetailResponse'
} as const;

export const MedicineSearchResponseSchema = {
    properties: {
        query: {
            type: 'string',
            title: 'Query'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        limit: {
            type: 'integer',
            title: 'Limit'
        },
        skip: {
            type: 'integer',
            title: 'Skip'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/MedicineSummary'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['query', 'total', 'limit', 'skip', 'items'],
    title: 'MedicineSearchResponse'
} as const;

export const MedicineSummarySchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        brand_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand Name'
        },
        generic_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Generic Name'
        },
        dosage: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dosage'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'MedicineSummary'
} as const;

export const MedicineUpdateSchema = {
    properties: {
        brand_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand Name'
        },
        generic_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Generic Name'
        },
        manufacturer: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Manufacturer'
        },
        purpose: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Purpose'
        },
        indications: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Indications'
        },
        warnings: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Warnings'
        },
        dosage: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dosage'
        },
        contraindications: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contraindications'
        },
        adverse_reactions: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Adverse Reactions'
        },
        side_effects: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Side Effects'
        }
    },
    type: 'object',
    title: 'MedicineUpdate'
} as const;

export const PasswordResetResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'PasswordResetResponse',
    description: 'Standard password reset response.'
} as const;

export const ResetPasswordRequestSchema = {
    properties: {
        token: {
            type: 'string',
            minLength: 1,
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'ResetPasswordRequest',
    description: 'Reset password request payload.'
} as const;

export const SearchHistoryCreateSchema = {
    properties: {
        query_text: {
            type: 'string',
            title: 'Query Text'
        },
        item_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Item Type'
        }
    },
    type: 'object',
    required: ['query_text'],
    title: 'SearchHistoryCreate'
} as const;

export const SearchHistoryListSchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/SearchHistoryResponse'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total', 'items'],
    title: 'SearchHistoryList'
} as const;

export const SearchHistoryResponseSchema = {
    properties: {
        query_text: {
            type: 'string',
            title: 'Query Text'
        },
        item_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Item Type'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        user_id: {
            type: 'integer',
            title: 'User Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['query_text', 'id', 'user_id', 'created_at'],
    title: 'SearchHistoryResponse'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserReadSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserRead'
} as const;

export const UserUpdateSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;