// This file is auto-generated by @hey-api/openapi-ts

export type AILogResponse = {
    total: number;
    items: Array<ChatHistoryItem>;
    page: number;
    limit: number;
};

export type Body_login_access_token_api_v1_auth_login_access_token_post = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_login_access_token_api_v1_login_access_token_post = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_login_alias_api_v1_auth_login_post = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BookmarkCreate = {
    item_type: string;
    item_neo4j_id: string;
};

export type BookmarkList = {
    total: number;
    items: Array<BookmarkResponse>;
};

export type BookmarkResponse = {
    item_type: string;
    item_neo4j_id: string;
    id: number;
    user_id: number;
    created_at: string;
};

export type ChatHistoryItem = {
    id: number;
    message: string;
    response: string;
    intent?: (string | null);
    created_at: string;
};

export type ChatHistoryList = {
    total: number;
    items: Array<ChatHistoryItem>;
};

export type ChatMessageRequest = {
    message: string;
};

export type ChatMessageResponse = {
    answer: string;
    entities?: Array<(string)>;
    sources?: Array<(string)>;
    warnings?: Array<(string)>;
};

export type DiseaseCreate = {
    name: string;
    category?: (string | null);
    severity?: (string | null);
    description?: (string | null);
    /**
     * List of medicine names that treat this disease
     */
    treatments?: Array<(string)>;
};

/**
 * Disease detail response with symptoms.
 */
export type DiseaseDetailResponse = {
    id?: (string | null);
    name: string;
    category?: (string | null);
    severity?: (string | null);
    description?: (string | null);
    symptoms?: Array<DiseaseSymptom>;
    /**
     * Medicine names
     */
    treatments?: Array<(string)>;
};

/**
 * Disease basic response.
 */
export type DiseaseResponse = {
    id?: (string | null);
    name: string;
    category?: (string | null);
    severity?: (string | null);
    description?: (string | null);
};

/**
 * Disease search response.
 */
export type DiseaseSearchResponse = {
    total: number;
    limit: number;
    items: Array<DiseaseResponse>;
};

/**
 * Disease symptom model.
 */
export type DiseaseSymptom = {
    name: string;
    description?: (string | null);
};

/**
 * Response for medicines that treat a specific disease.
 */
export type DiseaseTreatmentResponse = {
    disease_name: string;
    /**
     * Medicine list with basic details
     */
    treatments?: Array<{
        [key: string]: unknown;
    }>;
    total: number;
};

export type DiseaseUpdate = {
    name?: (string | null);
    category?: (string | null);
    severity?: (string | null);
    description?: (string | null);
    treatments?: (Array<(string)> | null);
};

/**
 * Forgot password request payload.
 */
export type ForgotPasswordRequest = {
    email: string;
};

export type GraphNode = {
    id: string;
    label: string;
    properties: {
        [key: string]: unknown;
    };
};

export type GraphRelationship = {
    source: string;
    target: string;
    type: string;
    properties: {
        [key: string]: unknown;
    };
};

export type GraphResponse = {
    nodes: Array<GraphNode>;
    links: Array<GraphRelationship>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Request to check interactions between drugs.
 */
export type InteractionCheckRequest = {
    drug_names: Array<(string)>;
};

/**
 * Response for interaction check.
 */
export type InteractionCheckResponse = {
    results?: Array<InteractionResult>;
};

/**
 * Detailed interaction between two specific drugs.
 */
export type InteractionDetailResponse = {
    drug_1: string;
    drug_2: string;
    has_interaction: boolean;
    severity?: (string | null);
    description?: (string | null);
    message?: (string | null);
};

/**
 * List of all interactions for a specific drug.
 */
export type InteractionListResponse = {
    drug_name: string;
    interactions?: Array<InteractionResult>;
    total: number;
    message?: (string | null);
};

/**
 * Interaction result between two drugs.
 */
export type InteractionResult = {
    drug_1: string;
    drug_2: string;
    has_interaction: boolean;
    severity?: (string | null);
    description?: (string | null);
};

/**
 * Summary of drug combination analysis.
 */
export type InteractionSummaryResponse = {
    drug_names: Array<(string)>;
    interactions: Array<InteractionResult>;
    is_safe: boolean;
    warnings?: Array<(string)>;
    summary: string;
};

export type MedicineCreate = {
    name: string;
    brand_name?: (string | null);
    generic_name?: (string | null);
    manufacturer?: (string | null);
    purpose?: (string | null);
    indications?: (string | null);
    warnings?: (string | null);
    dosage?: (string | null);
    contraindications?: (string | null);
    adverse_reactions?: (string | null);
    side_effects?: (string | null);
};

export type MedicineDetailResponse = {
    name: string;
    brand_name?: (string | null);
    generic_name?: (string | null);
    manufacturer?: (string | null);
    purpose?: (string | null);
    indications?: (string | null);
    warnings?: (string | null);
    dosage?: (string | null);
    contraindications?: (string | null);
    adverse_reactions?: (string | null);
    side_effects?: (string | null);
    updated_at?: (string | null);
    ingredients?: Array<(string)>;
    manufacturers?: Array<(string)>;
    treated_diseases?: Array<(string)>;
    interactions?: Array<{
        [key: string]: unknown;
    }>;
};

export type MedicineSearchResponse = {
    query: string;
    total: number;
    limit: number;
    skip: number;
    items: Array<MedicineSummary>;
};

export type MedicineSummary = {
    name: string;
    brand_name?: (string | null);
    generic_name?: (string | null);
    dosage?: (string | null);
};

export type MedicineUpdate = {
    brand_name?: (string | null);
    generic_name?: (string | null);
    manufacturer?: (string | null);
    purpose?: (string | null);
    indications?: (string | null);
    warnings?: (string | null);
    dosage?: (string | null);
    contraindications?: (string | null);
    adverse_reactions?: (string | null);
    side_effects?: (string | null);
};

/**
 * Standard password reset response.
 */
export type PasswordResetResponse = {
    message: string;
};

/**
 * Reset password request payload.
 */
export type ResetPasswordRequest = {
    token: string;
    new_password: string;
};

export type SearchHistoryCreate = {
    query_text: string;
    item_type?: (string | null);
};

export type SearchHistoryList = {
    total: number;
    items: Array<SearchHistoryResponse>;
};

export type SearchHistoryResponse = {
    query_text: string;
    item_type?: (string | null);
    id: number;
    user_id: number;
    created_at: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UserCreate = {
    email: string;
    full_name?: (string | null);
    is_active?: boolean;
    password: string;
};

export type UserRead = {
    email: string;
    full_name?: (string | null);
    is_active?: boolean;
    id: number;
    created_at?: (string | null);
    is_superuser?: boolean;
};

export type UserUpdate = {
    full_name?: (string | null);
    is_active?: (boolean | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AdminRebuildGraphApiV1AdminRebuildGraphPostResponse = (unknown);

export type AdminResetGraphApiV1AdminGraphResetPostData = {
    /**
     * Must be true to actually delete data
     */
    confirm?: boolean;
    /**
     * If true, only clean test/dummy data
     */
    testOnly?: boolean;
};

export type AdminResetGraphApiV1AdminGraphResetPostResponse = (unknown);

export type AdminGraphStatsApiV1AdminGraphStatsGetResponse = (unknown);

export type AdminGetUsersApiV1AdminUsersGetData = {
    limit?: number;
    skip?: number;
};

export type AdminGetUsersApiV1AdminUsersGetResponse = (unknown);

export type AdminUpdateUserRoleApiV1AdminUsersIdRolePutData = {
    id: number;
    isSuperuser: boolean;
};

export type AdminUpdateUserRoleApiV1AdminUsersIdRolePutResponse = (unknown);

export type AdminUpdateUserStatusApiV1AdminUsersIdStatusPutData = {
    id: number;
    isActive: boolean;
};

export type AdminUpdateUserStatusApiV1AdminUsersIdStatusPutResponse = (unknown);

export type AdminGetStatsApiV1AdminStatsGetResponse = (unknown);

export type AdminGetAiLogsApiV1AdminAiLogsGetData = {
    limit?: number;
    page?: number;
    userId?: (number | null);
};

export type AdminGetAiLogsApiV1AdminAiLogsGetResponse = (AILogResponse);

export type AdminCreateMedicineApiV1AdminMedicinesPostData = {
    requestBody: MedicineCreate;
};

export type AdminCreateMedicineApiV1AdminMedicinesPostResponse = (MedicineDetailResponse);

export type AdminUpdateMedicineApiV1AdminMedicinesIdPutData = {
    id: string;
    requestBody: MedicineUpdate;
};

export type AdminUpdateMedicineApiV1AdminMedicinesIdPutResponse = (MedicineDetailResponse);

export type AdminDeleteMedicineApiV1AdminMedicinesIdDeleteData = {
    id: string;
};

export type AdminDeleteMedicineApiV1AdminMedicinesIdDeleteResponse = (unknown);

export type AdminCreateDiseaseApiV1AdminDiseasesPostData = {
    requestBody: DiseaseCreate;
};

export type AdminCreateDiseaseApiV1AdminDiseasesPostResponse = (DiseaseDetailResponse);

export type AdminUpdateDiseaseApiV1AdminDiseasesIdPutData = {
    id: string;
    requestBody: DiseaseUpdate;
};

export type AdminUpdateDiseaseApiV1AdminDiseasesIdPutResponse = (DiseaseDetailResponse);

export type AdminDeleteDiseaseApiV1AdminDiseasesIdDeleteData = {
    id: string;
};

export type AdminDeleteDiseaseApiV1AdminDiseasesIdDeleteResponse = (unknown);

export type LoginAccessTokenApiV1AuthLoginAccessTokenPostData = {
    formData: Body_login_access_token_api_v1_auth_login_access_token_post;
};

export type LoginAccessTokenApiV1AuthLoginAccessTokenPostResponse = (Token);

export type LoginAliasApiV1AuthLoginPostData = {
    formData: Body_login_alias_api_v1_auth_login_post;
};

export type LoginAliasApiV1AuthLoginPostResponse = (Token);

export type ForgotPasswordApiV1AuthForgotPasswordPostData = {
    requestBody: ForgotPasswordRequest;
};

export type ForgotPasswordApiV1AuthForgotPasswordPostResponse = (PasswordResetResponse);

export type ResetPasswordApiV1AuthResetPasswordPostData = {
    requestBody: ResetPasswordRequest;
};

export type ResetPasswordApiV1AuthResetPasswordPostResponse = (PasswordResetResponse);

export type RegisterAliasApiV1AuthRegisterPostData = {
    requestBody: UserCreate;
};

export type RegisterAliasApiV1AuthRegisterPostResponse = (UserRead);

export type CreateBookmarkApiV1BookmarksPostData = {
    requestBody: BookmarkCreate;
};

export type CreateBookmarkApiV1BookmarksPostResponse = (BookmarkResponse);

export type GetBookmarksApiV1BookmarksGetData = {
    /**
     * Filter by 'Medicine' or 'Disease'
     */
    itemType?: (string | null);
    limit?: number;
    skip?: number;
};

export type GetBookmarksApiV1BookmarksGetResponse = (BookmarkList);

export type DeleteBookmarkApiV1BookmarksIdDeleteData = {
    id: number;
};

export type DeleteBookmarkApiV1BookmarksIdDeleteResponse = (unknown);

export type AskQuestionApiV1ChatAskPostData = {
    requestBody: ChatMessageRequest;
};

export type AskQuestionApiV1ChatAskPostResponse = (ChatMessageResponse);

export type GetChatHistoryApiV1ChatHistoryGetData = {
    limit?: number;
};

export type GetChatHistoryApiV1ChatHistoryGetResponse = (ChatHistoryList);

export type GetChatDetailApiV1ChatHistoryIdGetData = {
    id: number;
};

export type GetChatDetailApiV1ChatHistoryIdGetResponse = (ChatHistoryItem);

export type GetMedicineDebugApiV1DebugMedicineNameGetData = {
    name: string;
};

export type GetMedicineDebugApiV1DebugMedicineNameGetResponse = (unknown);

export type GetDiseaseDebugApiV1DebugDiseaseNameGetData = {
    name: string;
};

export type GetDiseaseDebugApiV1DebugDiseaseNameGetResponse = (unknown);

export type LoginAccessTokenApiV1LoginAccessTokenPostData = {
    formData: Body_login_access_token_api_v1_login_access_token_post;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostResponse = (Token);

export type SearchDiseasesApiV1DiseasesSearchGetData = {
    /**
     * Max results
     */
    limit?: number;
    /**
     * Search query
     */
    q: string;
    /**
     * Number of results to skip
     */
    skip?: number;
};

export type SearchDiseasesApiV1DiseasesSearchGetResponse = (DiseaseSearchResponse);

export type GetDiseaseDetailApiV1DiseasesDiseaseNameDetailGetData = {
    /**
     * Disease name
     */
    diseaseName: string;
};

export type GetDiseaseDetailApiV1DiseasesDiseaseNameDetailGetResponse = (DiseaseDetailResponse);

export type GetDiseaseTreatmentsApiV1DiseasesDiseaseNameTreatmentsGetData = {
    /**
     * Disease name
     */
    diseaseName: string;
    /**
     * Max results
     */
    limit?: number;
    /**
     * Number of results to skip
     */
    skip?: number;
};

export type GetDiseaseTreatmentsApiV1DiseasesDiseaseNameTreatmentsGetResponse = (DiseaseTreatmentResponse);

export type HealthCheckApiV1HealthGetResponse = (unknown);

export type RootHealthHealthGetResponse = (unknown);

export type GetInteractionHistoryCountApiV1InteractionsHistoryCountGetResponse = (unknown);

export type GetDrugInteractionsApiV1InteractionsDrugNameGetData = {
    /**
     * Medicine name
     */
    drugName: string;
    /**
     * Max results
     */
    limit?: number;
    /**
     * Number of results to skip
     */
    skip?: number;
};

export type GetDrugInteractionsApiV1InteractionsDrugNameGetResponse = (InteractionListResponse);

export type CheckMultipleInteractionsApiV1InteractionsCheckPostData = {
    requestBody: InteractionCheckRequest;
};

export type CheckMultipleInteractionsApiV1InteractionsCheckPostResponse = (InteractionCheckResponse);

export type AssessInteractionApiV1InteractionsDrug1WithDrug2GetData = {
    /**
     * First medicine name
     */
    drug1: string;
    /**
     * Second medicine name
     */
    drug2: string;
};

export type AssessInteractionApiV1InteractionsDrug1WithDrug2GetResponse = (InteractionDetailResponse);

export type AnalyzeDrugCombinationApiV1InteractionsAnalyzeCombinationPostData = {
    requestBody: InteractionCheckRequest;
};

export type AnalyzeDrugCombinationApiV1InteractionsAnalyzeCombinationPostResponse = (InteractionSummaryResponse);

export type SearchMedicinesApiV1MedicinesSearchGetData = {
    limit?: number;
    /**
     * Search query
     */
    q: string;
    skip?: number;
};

export type SearchMedicinesApiV1MedicinesSearchGetResponse = (MedicineSearchResponse);

export type GetMedicineDetailApiV1MedicinesNameDetailGetData = {
    /**
     * Medicine name
     */
    name: string;
};

export type GetMedicineDetailApiV1MedicinesNameDetailGetResponse = (MedicineDetailResponse);

export type GetMedicineByIdApiV1MedicinesIdGetData = {
    /**
     * Medicine ID (using name as ID)
     */
    id: string;
};

export type GetMedicineByIdApiV1MedicinesIdGetResponse = (MedicineDetailResponse);

export type TestNeo4jConnectionApiV1Neo4jTestGetResponse = (unknown);

export type GetNeo4jStatsApiV1Neo4jStatsGetResponse = (unknown);

export type GetGraphDataApiV1Neo4jGraphGetData = {
    limit?: number;
};

export type GetGraphDataApiV1Neo4jGraphGetResponse = (GraphResponse);

export type AddSearchHistoryApiV1SearchHistoryPostData = {
    requestBody: SearchHistoryCreate;
};

export type AddSearchHistoryApiV1SearchHistoryPostResponse = (SearchHistoryResponse);

export type GetSearchHistoryApiV1SearchHistoryGetData = {
    limit?: number;
    skip?: number;
};

export type GetSearchHistoryApiV1SearchHistoryGetResponse = (SearchHistoryList);

export type DeleteSearchHistoryApiV1SearchHistoryIdDeleteData = {
    id: number;
};

export type DeleteSearchHistoryApiV1SearchHistoryIdDeleteResponse = (unknown);

export type ReadCurrentUserApiV1UsersMeGetResponse = (UserRead);

export type UpdateCurrentUserApiV1UsersMePutData = {
    requestBody: UserUpdate;
};

export type UpdateCurrentUserApiV1UsersMePutResponse = (UserRead);

export type ReadUserApiV1UsersUserIdGetData = {
    userId: number;
};

export type ReadUserApiV1UsersUserIdGetResponse = (UserRead);

export type SignupApiV1UsersSignupPostData = {
    requestBody: UserCreate;
};

export type SignupApiV1UsersSignupPostResponse = (UserRead);