"""Add interaction history and fix search query

Revision ID: abb08b954b1a
Revises: cleanup_v1
Create Date: 2026-06-14 12:59:50.496496

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'abb08b954b1a'
down_revision = 'cleanup_v1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('drugs', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_history_id'), 'interaction_history', ['id'], unique=False)
    op.add_column('search_history', sa.Column('query_text', sa.String(), nullable=False))
    op.execute('DROP INDEX IF EXISTS ix_search_history_query_text')
    op.create_index(op.f('ix_search_history_query_text'), 'search_history', ['query_text'], unique=False)
    op.drop_column('search_history', 'query')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_history', sa.Column('query', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.execute('DROP INDEX IF EXISTS ix_search_history_query_text')
    op.create_index(op.f('ix_search_history_query_text'), 'search_history', ['query'], unique=False)
    op.drop_column('search_history', 'query_text')
    op.drop_index(op.f('ix_interaction_history_id'), table_name='interaction_history')
    op.drop_table('interaction_history')
    # ### end Alembic commands ###
